service: icalendar-bot

custom:
  myStage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      TELEGRAM_TOKEN: ${ssm:/app/${self:service}/dev/telegram_token}

provider:
  name: aws
  runtime: ruby2.7
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  memorySize: 128
  timeout: 7

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:CreateTable"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "*"

  logs:
    frameworkLambda: true

#layers:
#  gemlayer:
#    path: ruby

functions:
  icalendar:
    handler: webhook_handler.webhook
    layers:
      - arn:aws:lambda:eu-central-1:225265212598:layer:icalendarBotGemLayer:1
    environment:
      APP_NAME: icalendar
      GEM_PATH: /opt/2.7.0
      TELEGRAM_BOT_API_TOKEN: ${ssm:/app/${self:service}/${self:custom.myStage}/telegram_token}
    events:
      - http:
          path: icalendar
          method: post
          cors: true

package:
  include:
    - webhook_handler.rb
    - app/**
    - config/**
    - lib/**
    - system/**
  exclude:
    - ruby/**
