service: icalendar-bot

provider:
  name: aws
  runtime: ruby2.7
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  memorySize: 128
  timeout: 7

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:CreateTable"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:ListTables"
        - 'dynamodb:DescribeTable'
        - 'dynamodb:BatchGetItem'
      Resource:
        - "*"

  logs:
    frameworkLambda: true

layers:
  gemlayer:
    path: ruby

functions:
  icalendar:
    handler: app/webhook_handler.WebhookHandler.call
    layers:
      - {Ref: GemlayerLambdaLayer }
    environment:
      APP_NAME: icalendar
      APP_ENV: ${self:custom.myStage}
      GEM_PATH: /opt/2.7.0
      SENTRY_DSN: ${ssm:/app/${self:service}/${self:custom.myStage}/sentry_dsn}
      TELEGRAM_BOT_API_TOKEN: ${ssm:/app/${self:service}/${self:custom.myStage}/telegram_token}
    events:
      - http:
          path: icalendar
          method: post
          cors: true

package:
  include:
    - webhook_handler.rb
    - app/**
    - config/**
    - lib/**
    - system/**
  exclude:
    - ruby/**


custom:
  myStage: ${opt:stage, self:provider.stage}
