service: icalendar-bot

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  memorySize: 128
  timeout: 7
  enviroment:
    TELEGRAM_TOKEN: ${ssm:/app/${self:service}/${self:provider.stage}/telegram_token}
  logs:
    frameworkLambda: true

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: icalendar
          method: post
          cors: true
