name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build App
        env:
          APP_ENV: test
        run: |
          gem install bundler -v 2.1.2 --no-doc
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: |
         bundle exec rubocop

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'

      - name: Setup AWS credentials
        run: |
          mkdir ~/.aws
          echo -e "[default]\naws_access_key_id=''\naws_secret_access_key=''" > ~/.aws/credentials

      - name: Run Tests
        run: |
          bundle exec rspec
