name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Build App
        env:
          RAILS_ENV: test
        run: |
          gem install bundler -v 2.1.2 --no-doc
          bundle install --jobs 4 --retry 3
      - name: Build and test with Rake
        run: |
          bundle exec rubocop
          bundle exec rspec
